---
- hosts: webservers
  become: yes
  tasks:
  - name: install webservers on ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="Debian"
  - name: start webservers
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"

  - name: install webserves on amazon
    yum: 
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"
  
  - name: start webservers on amazon
    service:
     name: httpd
     state: started
    when: ansible_os_family =="RedHat"

